# Generated by Django 5.2 on 2025-04-15 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['-registered_date'], 'verbose_name': 'Donor', 'verbose_name_plural': 'Donors'},
        ),
        migrations.AddField(
            model_name='donor',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('pending', 'Pending Verification')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='registered_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donor',
            name='total_donations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.CreateModel(
            name='DonorDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('amount_ml', models.PositiveIntegerField(default=450)),
                ('donation_date', models.DateField(auto_now_add=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donor')),
            ],
            options={
                'verbose_name': 'Donor Donation',
                'verbose_name_plural': 'Donor Donations',
                'ordering': ['-donation_date'],
            },
        ),
    ]
