# Generated by Django 5.2 on 2025-04-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_donor_options_donor_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='urgency',
            field=models.CharField(choices=[('critical', 'Critical - Immediate'), ('high', 'High - Within 24 hours'), ('medium', 'Medium - Within 3 days'), ('low', 'Low - Within a week')], default='medium', max_length=20),
        ),
    ]
