# Generated by Django 5.2 on 2025-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bloodrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='additional_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='contact_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=8),
        ),
    ]
