# Generated by Django 5.2 on 2025-04-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_bloodrequest_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
